# Generated by Django 4.1.1 on 2022-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplic", "0003_aluno_foto_professor_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="aluno",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="aluno",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, verbose_name="Twitter"),
        ),
        migrations.AddField(
            model_name="professor",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="professor",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="professor",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, verbose_name="Twitter"),
        ),
    ]
