# Generated by Django 4.1.1 on 2022-10-18 23:22

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("aplic", "0004_aluno_facebook_aluno_instagram_aluno_linkedin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="imagem",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to=aplic.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 260, "width": 420}},
                verbose_name="Imagem",
            ),
        ),
    ]
